### ISSUE TITLE
Question about Figure 3

### ISSUE THREAD

**Issue by tokaka22** [VEWOXIC/FITS#13]
Sorry to bother you again.
1. I would like to inquire about some details regarding Figure 3, where the base frequency is indicated as 20. My understanding is that this is because the highest peak in the amplitude spectrum (second row) corresponds to an x-coordinate value (frequency) of 20. Could you confirm if this interpretation is correct? 
2. Additionally, could you explain how 'its dominant periodicity is 24' is reached?
Thank you for your work~

![image](https://github.com/user-attachments/assets/a05dbf7c-a2c9-46e2-982a-1d853a12b4e2)

**Comment by VEWOXIC** [comment]
1) Yes, it is correct. The selected window is 480 and major periodicity is 24. Thus, we have 20 period of this periodicity pattern which correspond to the highest peak in the frequency of 20. 
2) This dataset is sampled hourly and shows a clear daily pattern (because this is a dataset from an electricial transformer). Thus, the dominant periodicity is 24 (24 hours per day).

**Comment by tokaka22** [comment]
I got it, thank you~
