### ISSUE TITLE
Question about the cutoff calculation.

### ISSUE THREAD

**Issue by mb-Ma** [VEWOXIC/FITS#9]
https://github.com/VEWOXIC/FITS/blob/0944309af2ca04f44553153102b3adaf431e15d9/run_longExp_F.py#L113

I am curious about the "+ 10" operation. Because I do not find the explanation in the paper.

Can you explain more?

**Comment by VEWOXIC** [comment]
This is a hyper-parameter and I almost randomly designit as this. the args.seq_len // args.base_T calculates its base frequency. The +1 and +10 is just adding **some redundancy when cutting the spectrum**. The *H_order to calculate the real cut_freq. so actually, when you use the H_order to assign a cut_freq, it is not cut at the exact frequency.

**Comment by mb-Ma** [comment]
Thank you for your quick reply. :-) It addresses my concerns. 
I tried some adaptive COF values, like top K amplitude-frequency. Badly, these all hurt the model. Do you have any insights into the COF design?

**Comment by mb-Ma** [comment]
It is. From the visualization of spectrums, we can observe that most high amplitude components are located in low frequency.  Another point is the top K amplitude selection strategy would break the continuity of the spectrum.

But as yet I cannot figure out one way that is better than fixed COF. It is hard to obtain an adaptive COF for each instance. There is a trade-off where a more optimal COF can be selected by power spectrum or information entropy but with more computation overhead.

**Comment by VEWOXIC** [comment]
So, you mean only model the top K frequency? Seems not a good idea hhh. 

We have never considered the adaptive COF when designing the FITS and it may not be suitable for this. But is definitely a good idea to design a frequency-domain model that can adaptively attend to frequency components that is more important to the instance.   

Further, we do not think further simplify the model is a meaningful topic since we design FITS is just to show there is not much information to learn with time series data alone.

**Comment by VEWOXIC** [comment]
if there is no further question, I will close this issue. Please feel free to reopen it.

**Comment by mb-Ma** [comment]
Sorry for my late reply. Thanks for your consecutive feedback. 

Good work. 👍
